server:
  port: 8081
spring:
  application:
    name: SuperSteps
  datasource:
    url: jdbc:postgresql://localhost:5432/super-recipes
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
