server:
  port: 8082
spring:
  application:
    name: SuperRecipes
  datasource:
    url: jdbc:postgresql://100.71.190.42:5432/recipes
    username: admin
    password: 2314
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
